POST http://localhost:5000/post/get-post
content-type: application/json

{
    "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    "post_image": "https://www.redditstatic.com/icon.png"
}