POST http://localhost:5000/
content-type: application/json

{
    "username": "Rami",
    "email": "Rami@gmail.com",
    "image_url": "https://www.reddit.com/r/Re_Zero/comments/jizfrn/media_i_created_emilia_in_reddit_avatar/",
    "password": "123",
    "confirm_password":"123"
}